---
extends: default

rules:
  braces:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
  comments-indentation: false
  document-end:
    present: true
  document-start:
    present: true
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
  line-length: false
  truthy:
    allowed-values: ["true", "false"]

ignore-from-file: .gitignore
...
