license = "MIT"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "~3.13"
ansible = "~11.2"

[tool.poetry.group.dev.dependencies]
ansible-lint = "~25.1"
lefthook = "~1.10"
yamllint = "~1.35"
