---
- name: Ensure kitty data directory is exist
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/kitty"
    mode: '0700'
    state: directory
  when: desired_state == 'present'

- name: Remove kitty data directory
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/kitty"
    state: absent
  when: desired_state == 'absent'

- name: Setup kitty config
  ansible.builtin.copy:
    src: files/kitty.conf
    dest: "{{ xdg_config_home }}/kitty/kitty.conf"
    mode: '0600'
  when: desired_state == 'present'

- name: Ensure kitty themes directory is exist
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/kitty/themes"
    mode: '0700'
    state: directory
  when: desired_state == 'present'

- name: Setup kitty themes
  ansible.builtin.copy:
    src: "themes/"
    dest: "{{ xdg_config_home }}/kitty/themes/"
    mode: '0600'
  when: desired_state == 'present'
...
