---
- name: Fail if the OS is not supported
  ansible.builtin.fail:
    msg: "This system isn't supported, please add support."
  when: ansible_facts['os_family'] not in ['Darwin', 'Linux']

- name: Ensure homebrew is installed
  community.general.homebrew:
    state: present
    update_homebrew: true
  when: desired_state == 'present'

- name: Ensure brew taps is {{ desired_state }}
  community.general.homebrew_tap:
    name: "{{ brew_packages.taps }}"
    state: "{{ desired_state }}"
  when: (desired_state == 'present' or desired_state == 'absent') and brew_packages.taps | length > 0

- name: Ensure brew formulas is {{ desired_state }}
  community.general.homebrew:
    name: "{{ brew_packages.formulas | reject('match', 'python') | list }}"
    state: "{{ desired_state }}"
  when: (desired_state == 'present' or desired_state == 'absent') and brew_packages.formulas | length > 0

- name: Ensure brew casks is {{ desired_state }}
  community.general.homebrew_cask:
    name: "{{ brew_packages.casks }}"
    state: "{{ desired_state }}"
  when: (desired_state == 'present' or desired_state == 'absent') and brew_packages.casks | length > 0

- name: Uninstall homebrew
  community.general.homebrew:
    state: absent
  when: desired_state == 'absent'
...
