---
- name: Ensure tmux data directory is exist
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/tmux"
    mode: '0700'
    state: directory
  when: desired_state == 'present'

- name: Checkout tmux plugins
  ansible.builtin.include_role:
    name: git
    tasks_from: checkout
  vars:
    git_repos:
      - repo: 'https://github.com/tmux-plugins/tpm.git'
        dest: "{{ xdg_data_home }}/tmux/plugins/tpm"

- name: Remove tmux data
  ansible.builtin.file:
    path: "{{ xdg_data_home }}/tmux"
    state: absent
  when: desired_state == 'absent'

- name: Ensure tmux config directory is exist
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/tmux"
    mode: '0700'
    state: directory
  when: desired_state == 'present'

- name: Setup tmux config
  ansible.builtin.copy:
    src: files/tmux.conf.j2
    dest: "{{ xdg_config_home }}/tmux/tmux.conf"
    mode: '0600'
  when: desired_state == 'present'

- name: Remove tmux config
  ansible.builtin.file:
    path: "{{ xdg_config_home }}/tmux"
    state: absent
  when: desired_state == 'absent'
...
