colors:
  cursor:
    cursor: '#ffffff'
  primary:
    background: '0x1d2021'

env:
  TERM: screen-256color

font:
  bold:
    family: Hack Nerd Font Mono
    style: Regular
  bold_italic:
    family: Hack Nerd Font Mono
  italic:
    family: Hack Nerd Font Mono
  normal:
    family: Hack Nerd Font Mono
  size: 13.0

tabspaces: 4

window:
  padding:
    x: 0
    y: 0
