version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  checkmake: &checkmake
    lint-command: 'checkmake'
    lint-formats:
      - '%f:%l:%c: %m'

  dockerfile: &dockerfile
    lint-command: 'hadolint'
    lint-formats:
      - '%f:%l %m'

  eslint: &eslint
    format-command: 'npx eslint -f compact --stdin --fix'
    format-stdin: true
    lint-command: 'npx eslint -f compact --stdin'
    lint-formats:
      - '%f:%l:%c: %m'

  jq: &jq
    lint-command: 'npx jq .'


  prettier: &prettier
    format-command: 'npx prettier'
    format-stdin: true

  luacheck: &luacheck
    lint-command: 'luacheck -'
    lint-formats:
      - '%f:%l:%c: %m'

  markdown: &markdown
    format-command: 'npx eslint -f compact --stdin --fix'
    format-stdin: true
    lint-command: 'npx markdownlint --stdin'
    lint-formats:
      - '%f:%l:%c: %m'

  shellcheck: &shellcheck
    lint-command: 'shellcheck -f gcc -x'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'
      - '%f:%l:%c: %tarning: %m'

  shfmt: &shfmt
    format-command: 'shfmt -ci -s -bn'
    format-stdin: true

  stylelint: &stylelint
    format-command: 'npx stylelint -f compact --stdin --fix'
    format-stdin: true
    lint-command: 'npx stylelint -f compact --stdin'
    lint-ignore-exit-code: false
    lint-formats:
      - '%f:%l:%c: %m'

  stylua: &stylua
    format-command: 'stylua -'
    format-stdin: true

  yamllint: &yamllint
    lint-command: 'yamllint -f parsable -'

languages:
  bash:
    - <<: *shellcheck
    - <<: *shfmt

  css:
    - <<: *prettier
    - <<: *stylelint

  dockerfile:
    - <<: *dockerfile

  graphql:
    - <<: *prettier

  html:
    - <<: *prettier

  javascript:
    - <<: *prettier
    - <<: *eslint

  javascriptreact:
    - <<: *prettier
    - <<: *eslint

  json:
    - <<: *prettier
    - <<: *jq

  markdown:
    - <<: *prettier
    - <<: *markdown

  typescript:
    - <<: *prettier
    - <<: *eslint

  typescriptreact:
    - <<: *prettier
    - <<: *eslint

  lua:
    - <<: *luacheck
    - <<: *stylua

  make:
    - <<: *checkmake

  yaml:
    - <<: *prettier
    - <<: *yamllint

  zsh:
    - <<: *shellcheck
    - <<: *shfmt
